# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProcedureDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProcedureDialog(object):
    def setupUi(self, ProcedureDialog):
        ProcedureDialog.setObjectName("ProcedureDialog")
        ProcedureDialog.resize(1106, 876)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        ProcedureDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProcedureDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.label = QtWidgets.QLabel(ProcedureDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.txtProcedureName = QtWidgets.QLineEdit(ProcedureDialog)
        self.txtProcedureName.setAlignment(QtCore.Qt.AlignCenter)
        self.txtProcedureName.setObjectName("txtProcedureName")
        self.horizontalLayout_7.addWidget(self.txtProcedureName)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.tabWidget = QtWidgets.QTabWidget(ProcedureDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rbValue = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbValue.setChecked(True)
        self.rbValue.setObjectName("rbValue")
        self.gridLayout_3.addWidget(self.rbValue, 0, 0, 1, 1)
        self.hlayoutRule = QtWidgets.QHBoxLayout()
        self.hlayoutRule.setObjectName("hlayoutRule")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayoutRule.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.hlayoutRule.addWidget(self.label_4)
        self.cbRuleCompare = QtWidgets.QComboBox(self.groupBox_2)
        self.cbRuleCompare.setCurrentText("")
        self.cbRuleCompare.setObjectName("cbRuleCompare")
        self.hlayoutRule.addWidget(self.cbRuleCompare)
        self.cbRuleBool = QtWidgets.QComboBox(self.groupBox_2)
        self.cbRuleBool.setObjectName("cbRuleBool")
        self.hlayoutRule.addWidget(self.cbRuleBool)
        self.txtRuleVal = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtRuleVal.setAlignment(QtCore.Qt.AlignCenter)
        self.txtRuleVal.setObjectName("txtRuleVal")
        self.hlayoutRule.addWidget(self.txtRuleVal)
        self.lblRuleUnit = QtWidgets.QLabel(self.groupBox_2)
        self.lblRuleUnit.setObjectName("lblRuleUnit")
        self.hlayoutRule.addWidget(self.lblRuleUnit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayoutRule.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.hlayoutRule, 0, 1, 1, 1)
        self.rbEvent = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbEvent.setObjectName("rbEvent")
        self.gridLayout_3.addWidget(self.rbEvent, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.cbEvent = QtWidgets.QComboBox(self.groupBox_2)
        self.cbEvent.setEnabled(False)
        self.cbEvent.setObjectName("cbEvent")
        self.horizontalLayout_5.addWidget(self.cbEvent)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.rbManual = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbManual.setObjectName("rbManual")
        self.gridLayout_3.addWidget(self.rbManual, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 475))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.hlayoutAction = QtWidgets.QHBoxLayout()
        self.hlayoutAction.setObjectName("hlayoutAction")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.hlayoutAction.addWidget(self.label_2)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.hlayoutAction.addWidget(self.label_6)
        self.cbActionBool = QtWidgets.QComboBox(self.groupBox_3)
        self.cbActionBool.setObjectName("cbActionBool")
        self.hlayoutAction.addWidget(self.cbActionBool)
        self.txtActionVal = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtActionVal.setAlignment(QtCore.Qt.AlignCenter)
        self.txtActionVal.setObjectName("txtActionVal")
        self.hlayoutAction.addWidget(self.txtActionVal)
        self.lblActionUnit = QtWidgets.QLabel(self.groupBox_3)
        self.lblActionUnit.setObjectName("lblActionUnit")
        self.hlayoutAction.addWidget(self.lblActionUnit)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayoutAction.addItem(spacerItem6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.hlayoutAction.addWidget(self.label_7)
        self.txtDelay = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtDelay.setMaxLength(10)
        self.txtDelay.setAlignment(QtCore.Qt.AlignCenter)
        self.txtDelay.setObjectName("txtDelay")
        self.hlayoutAction.addWidget(self.txtDelay)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.hlayoutAction.addWidget(self.label_8)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlayoutAction.addItem(spacerItem7)
        self.btnAddAction = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAddAction.setObjectName("btnAddAction")
        self.hlayoutAction.addWidget(self.btnAddAction)
        self.verticalLayout_3.addLayout(self.hlayoutAction)
        self.scAction = QtWidgets.QScrollArea(self.groupBox_3)
        self.scAction.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scAction.setWidgetResizable(True)
        self.scAction.setObjectName("scAction")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1044, 361))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.fmActions = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.fmActions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmActions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fmActions.setObjectName("fmActions")
        self.gridLayout.addWidget(self.fmActions, 0, 0, 1, 1)
        self.scAction.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scAction)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem8 = QtWidgets.QSpacerItem(281, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridPid = QtWidgets.QGridLayout()
        self.gridPid.setObjectName("gridPid")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.gridPid.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.gridPid.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.gridPid.addWidget(self.label_10, 2, 0, 1, 1)
        self.txtTarget = QtWidgets.QLineEdit(self.tab_2)
        self.txtTarget.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTarget.setObjectName("txtTarget")
        self.gridPid.addWidget(self.txtTarget, 2, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridPid)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.txtdt = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtdt.setAlignment(QtCore.Qt.AlignCenter)
        self.txtdt.setObjectName("txtdt")
        self.gridLayout_4.addWidget(self.txtdt, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 0, 1, 1)
        self.txtP = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtP.setAlignment(QtCore.Qt.AlignCenter)
        self.txtP.setObjectName("txtP")
        self.gridLayout_4.addWidget(self.txtP, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.txtI = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtI.setAlignment(QtCore.Qt.AlignCenter)
        self.txtI.setObjectName("txtI")
        self.gridLayout_4.addWidget(self.txtI, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 3, 0, 1, 1)
        self.txtD = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtD.setAlignment(QtCore.Qt.AlignCenter)
        self.txtD.setObjectName("txtD")
        self.gridLayout_4.addWidget(self.txtD, 3, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.txtAverage = QtWidgets.QLineEdit(self.groupBox)
        self.txtAverage.setEnabled(True)
        self.txtAverage.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAverage.setObjectName("txtAverage")
        self.gridLayout_6.addWidget(self.txtAverage, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 2, 1, 1)
        self.txtWarmup = QtWidgets.QLineEdit(self.groupBox)
        self.txtWarmup.setEnabled(True)
        self.txtWarmup.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWarmup.setObjectName("txtWarmup")
        self.gridLayout_6.addWidget(self.txtWarmup, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 1, 2, 1, 1)
        self.txtOffset = QtWidgets.QLineEdit(self.groupBox)
        self.txtOffset.setEnabled(True)
        self.txtOffset.setAlignment(QtCore.Qt.AlignCenter)
        self.txtOffset.setObjectName("txtOffset")
        self.gridLayout_6.addWidget(self.txtOffset, 2, 1, 1, 1)
        self.lblUnit = QtWidgets.QLabel(self.groupBox)
        self.lblUnit.setObjectName("lblUnit")
        self.gridLayout_6.addWidget(self.lblUnit, 2, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 2, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem10)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        spacerItem11 = QtWidgets.QSpacerItem(281, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem12 = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem12)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem13)
        self.gbTimerStart = QtWidgets.QGroupBox(self.tab_3)
        self.gbTimerStart.setObjectName("gbTimerStart")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gbTimerStart)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_31 = QtWidgets.QLabel(self.gbTimerStart)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gbTimerStart)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 1, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cbTimerStartComp = QtWidgets.QComboBox(self.gbTimerStart)
        self.cbTimerStartComp.setObjectName("cbTimerStartComp")
        self.cbTimerStartComp.addItem("")
        self.cbTimerStartComp.addItem("")
        self.horizontalLayout_12.addWidget(self.cbTimerStartComp)
        self.txtTimerStart = QtWidgets.QLineEdit(self.gbTimerStart)
        self.txtTimerStart.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTimerStart.setObjectName("txtTimerStart")
        self.horizontalLayout_12.addWidget(self.txtTimerStart)
        self.lblTimerStartUnit = QtWidgets.QLabel(self.gbTimerStart)
        self.lblTimerStartUnit.setObjectName("lblTimerStartUnit")
        self.horizontalLayout_12.addWidget(self.lblTimerStartUnit)
        self.gridLayout_7.addLayout(self.horizontalLayout_12, 1, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.gbTimerStart)
        self.gbTimerStop = QtWidgets.QGroupBox(self.tab_3)
        self.gbTimerStop.setObjectName("gbTimerStop")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gbTimerStop)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_33 = QtWidgets.QLabel(self.gbTimerStop)
        self.label_33.setObjectName("label_33")
        self.gridLayout_8.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gbTimerStop)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 1, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.cbTimerStopComp = QtWidgets.QComboBox(self.gbTimerStop)
        self.cbTimerStopComp.setObjectName("cbTimerStopComp")
        self.cbTimerStopComp.addItem("")
        self.cbTimerStopComp.addItem("")
        self.horizontalLayout_16.addWidget(self.cbTimerStopComp)
        self.txtTimerStop = QtWidgets.QLineEdit(self.gbTimerStop)
        self.txtTimerStop.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTimerStop.setObjectName("txtTimerStop")
        self.horizontalLayout_16.addWidget(self.txtTimerStop)
        self.lblTimerStopUnit = QtWidgets.QLabel(self.gbTimerStop)
        self.lblTimerStopUnit.setObjectName("lblTimerStopUnit")
        self.horizontalLayout_16.addWidget(self.lblTimerStopUnit)
        self.gridLayout_8.addLayout(self.horizontalLayout_16, 1, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.gbTimerStop)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_13.addWidget(self.label_34)
        self.txtTimerMinTime = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtTimerMinTime.setEnabled(True)
        self.txtTimerMinTime.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTimerMinTime.setObjectName("txtTimerMinTime")
        self.horizontalLayout_13.addWidget(self.txtTimerMinTime)
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_13.addWidget(self.label_32)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.chkTimerContinuous = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkTimerContinuous.setObjectName("chkTimerContinuous")
        self.verticalLayout_6.addWidget(self.chkTimerContinuous)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem14)
        self.horizontalLayout_17.addLayout(self.verticalLayout_7)
        spacerItem15 = QtWidgets.QSpacerItem(268, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem15)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gbOptions = QtWidgets.QGroupBox(ProcedureDialog)
        self.gbOptions.setObjectName("gbOptions")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbOptions)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chkCritical = QtWidgets.QCheckBox(self.gbOptions)
        self.chkCritical.setObjectName("chkCritical")
        self.horizontalLayout.addWidget(self.chkCritical)
        self.horizontalLayout_9.addWidget(self.gbOptions)
        self.gbNotify = QtWidgets.QGroupBox(ProcedureDialog)
        self.gbNotify.setObjectName("gbNotify")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.gbNotify)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chkEmail = QtWidgets.QCheckBox(self.gbNotify)
        self.chkEmail.setEnabled(False)
        self.chkEmail.setObjectName("chkEmail")
        self.horizontalLayout_6.addWidget(self.chkEmail)
        self.chkText = QtWidgets.QCheckBox(self.gbNotify)
        self.chkText.setEnabled(False)
        self.chkText.setObjectName("chkText")
        self.horizontalLayout_6.addWidget(self.chkText)
        self.chkSlack = QtWidgets.QCheckBox(self.gbNotify)
        self.chkSlack.setObjectName("chkSlack")
        self.horizontalLayout_6.addWidget(self.chkSlack)
        self.horizontalLayout_9.addWidget(self.gbNotify)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.gbContact = QtWidgets.QGroupBox(ProcedureDialog)
        self.gbContact.setObjectName("gbContact")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbContact)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtText = QtWidgets.QLineEdit(self.gbContact)
        self.txtText.setObjectName("txtText")
        self.gridLayout_2.addWidget(self.txtText, 1, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem16, 0, 3, 1, 1)
        self.lblText = QtWidgets.QLabel(self.gbContact)
        self.lblText.setObjectName("lblText")
        self.gridLayout_2.addWidget(self.lblText, 1, 1, 1, 1)
        self.lblEmail = QtWidgets.QLabel(self.gbContact)
        self.lblEmail.setObjectName("lblEmail")
        self.gridLayout_2.addWidget(self.lblEmail, 0, 1, 1, 1)
        self.txtEmail = QtWidgets.QLineEdit(self.gbContact)
        self.txtEmail.setObjectName("txtEmail")
        self.gridLayout_2.addWidget(self.txtEmail, 0, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem17, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem18, 1, 3, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem19, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.gbContact)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem20)
        self.btnDone = QtWidgets.QPushButton(ProcedureDialog)
        self.btnDone.setObjectName("btnDone")
        self.horizontalLayout_2.addWidget(self.btnDone)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem21)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ProcedureDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ProcedureDialog)

    def retranslateUi(self, ProcedureDialog):
        _translate = QtCore.QCoreApplication.translate
        ProcedureDialog.setWindowTitle(_translate("ProcedureDialog", "Add/Edit Procedure"))
        self.label.setText(_translate("ProcedureDialog", "Name"))
        self.txtProcedureName.setText(_translate("ProcedureDialog", "My Procedure"))
        self.groupBox_2.setTitle(_translate("ProcedureDialog", "Rule"))
        self.rbValue.setText(_translate("ProcedureDialog", "Value"))
        self.label_4.setText(_translate("ProcedureDialog", "is"))
        self.lblRuleUnit.setText(_translate("ProcedureDialog", "TextLabel"))
        self.rbEvent.setText(_translate("ProcedureDialog", "Event"))
        self.rbManual.setText(_translate("ProcedureDialog", "Manual"))
        self.groupBox_3.setTitle(_translate("ProcedureDialog", "Action"))
        self.label_2.setText(_translate("ProcedureDialog", "Set"))
        self.label_6.setText(_translate("ProcedureDialog", "to"))
        self.lblActionUnit.setText(_translate("ProcedureDialog", "TextLabel"))
        self.label_7.setText(_translate("ProcedureDialog", "Delay:"))
        self.txtDelay.setText(_translate("ProcedureDialog", "0.0"))
        self.label_8.setText(_translate("ProcedureDialog", "s"))
        self.btnAddAction.setText(_translate("ProcedureDialog", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ProcedureDialog", "Basic"))
        self.label_17.setText(_translate("ProcedureDialog", "Write Channel:"))
        self.label_16.setText(_translate("ProcedureDialog", "Read Channel:"))
        self.label_10.setText(_translate("ProcedureDialog", "Target Value:"))
        self.txtTarget.setText(_translate("ProcedureDialog", "0.0"))
        self.groupBox_5.setTitle(_translate("ProcedureDialog", "PID"))
        self.label_11.setText(_translate("ProcedureDialog", "Time Step:"))
        self.txtdt.setText(_translate("ProcedureDialog", "0.0"))
        self.label_12.setText(_translate("ProcedureDialog", "P"))
        self.txtP.setText(_translate("ProcedureDialog", "0.0"))
        self.label_13.setText(_translate("ProcedureDialog", "I"))
        self.txtI.setText(_translate("ProcedureDialog", "0.0"))
        self.label_14.setText(_translate("ProcedureDialog", "D"))
        self.txtD.setText(_translate("ProcedureDialog", "0.0"))
        self.groupBox.setTitle(_translate("ProcedureDialog", "More Options"))
        self.txtAverage.setText(_translate("ProcedureDialog", "1"))
        self.label_18.setText(_translate("ProcedureDialog", "samples"))
        self.txtWarmup.setText(_translate("ProcedureDialog", "0"))
        self.label_19.setText(_translate("ProcedureDialog", "samples"))
        self.txtOffset.setText(_translate("ProcedureDialog", "0.0"))
        self.lblUnit.setText(_translate("ProcedureDialog", "Unit"))
        self.label_20.setText(_translate("ProcedureDialog", "Average"))
        self.label_21.setText(_translate("ProcedureDialog", "Warmup"))
        self.label_22.setText(_translate("ProcedureDialog", "Offset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ProcedureDialog", "PID"))
        self.gbTimerStart.setTitle(_translate("ProcedureDialog", "Start Condition"))
        self.label_31.setText(_translate("ProcedureDialog", "Channel:"))
        self.label_23.setText(_translate("ProcedureDialog", "Start when:"))
        self.cbTimerStartComp.setItemText(0, _translate("ProcedureDialog", ">"))
        self.cbTimerStartComp.setItemText(1, _translate("ProcedureDialog", "<"))
        self.txtTimerStart.setText(_translate("ProcedureDialog", "0.0"))
        self.lblTimerStartUnit.setText(_translate("ProcedureDialog", "Unit"))
        self.gbTimerStop.setTitle(_translate("ProcedureDialog", "Stop Condition"))
        self.label_33.setText(_translate("ProcedureDialog", "Channel:"))
        self.label_24.setText(_translate("ProcedureDialog", "Stop when:"))
        self.cbTimerStopComp.setItemText(0, _translate("ProcedureDialog", ">"))
        self.cbTimerStopComp.setItemText(1, _translate("ProcedureDialog", "<"))
        self.txtTimerStop.setText(_translate("ProcedureDialog", "0.0"))
        self.lblTimerStopUnit.setText(_translate("ProcedureDialog", "Unit"))
        self.groupBox_4.setTitle(_translate("ProcedureDialog", "Options"))
        self.label_34.setText(_translate("ProcedureDialog", "Minimum Time:"))
        self.txtTimerMinTime.setText(_translate("ProcedureDialog", "0"))
        self.label_32.setText(_translate("ProcedureDialog", "s"))
        self.chkTimerContinuous.setText(_translate("ProcedureDialog", "Continuous"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ProcedureDialog", "Timer"))
        self.gbOptions.setTitle(_translate("ProcedureDialog", "Options"))
        self.chkCritical.setText(_translate("ProcedureDialog", "Critical"))
        self.gbNotify.setTitle(_translate("ProcedureDialog", "Notify"))
        self.chkEmail.setText(_translate("ProcedureDialog", "Email"))
        self.chkText.setText(_translate("ProcedureDialog", "Mobile"))
        self.chkSlack.setText(_translate("ProcedureDialog", "Slack"))
        self.gbContact.setTitle(_translate("ProcedureDialog", "Contact Information"))
        self.lblText.setText(_translate("ProcedureDialog", "Mobile"))
        self.lblEmail.setText(_translate("ProcedureDialog", "Email"))
        self.btnDone.setText(_translate("ProcedureDialog", "Done"))

