# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/PlotSettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotSettingsDialog(object):
    def setupUi(self, PlotSettingsDialog):
        PlotSettingsDialog.setObjectName("PlotSettingsDialog")
        PlotSettingsDialog.resize(693, 523)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        PlotSettingsDialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlotSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(PlotSettingsDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.rbXAuto = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbXAuto.setObjectName("rbXAuto")
        self.gridLayout.addWidget(self.rbXAuto, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.txtXMin = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtXMin.setObjectName("txtXMin")
        self.gridLayout.addWidget(self.txtXMin, 0, 2, 1, 1)
        self.rbXManual = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbXManual.setObjectName("rbXManual")
        self.gridLayout.addWidget(self.rbXManual, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.txtXMax = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtXMax.setObjectName("txtXMax")
        self.gridLayout.addWidget(self.txtXMax, 1, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chkXLog = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkXLog.setEnabled(False)
        self.chkXLog.setObjectName("chkXLog")
        self.gridLayout_2.addWidget(self.chkXLog, 1, 0, 1, 1)
        self.chkXGrid = QtWidgets.QCheckBox(self.groupBox_3)
        self.chkXGrid.setObjectName("chkXGrid")
        self.gridLayout_2.addWidget(self.chkXGrid, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(PlotSettingsDialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rbYAuto = QtWidgets.QRadioButton(self.groupBox_5)
        self.rbYAuto.setObjectName("rbYAuto")
        self.gridLayout_3.addWidget(self.rbYAuto, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.txtYMin = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtYMin.setObjectName("txtYMin")
        self.gridLayout_3.addWidget(self.txtYMin, 0, 2, 1, 1)
        self.rbYManual = QtWidgets.QRadioButton(self.groupBox_5)
        self.rbYManual.setObjectName("rbYManual")
        self.gridLayout_3.addWidget(self.rbYManual, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 1, 1, 1)
        self.txtYMax = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtYMax.setObjectName("txtYMax")
        self.gridLayout_3.addWidget(self.txtYMax, 1, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.chkYLog = QtWidgets.QCheckBox(self.groupBox_6)
        self.chkYLog.setObjectName("chkYLog")
        self.gridLayout_4.addWidget(self.chkYLog, 1, 0, 1, 1)
        self.chkYGrid = QtWidgets.QCheckBox(self.groupBox_6)
        self.chkYGrid.setObjectName("chkYGrid")
        self.gridLayout_4.addWidget(self.chkYGrid, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_7 = QtWidgets.QGroupBox(PlotSettingsDialog)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnColor = QtWidgets.QPushButton(self.groupBox_7)
        self.btnColor.setObjectName("btnColor")
        self.horizontalLayout_4.addWidget(self.btnColor)
        self.lblColor = QtWidgets.QLabel(self.groupBox_7)
        self.lblColor.setStyleSheet("padding: 0 11; background-color: red")
        self.lblColor.setFrameShape(QtWidgets.QFrame.Box)
        self.lblColor.setText("")
        self.lblColor.setObjectName("lblColor")
        self.horizontalLayout_4.addWidget(self.lblColor)
        spacerItem1 = QtWidgets.QSpacerItem(243, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btnDone = QtWidgets.QPushButton(PlotSettingsDialog)
        self.btnDone.setObjectName("btnDone")
        self.horizontalLayout_3.addWidget(self.btnDone)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(PlotSettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(PlotSettingsDialog)

    def retranslateUi(self, PlotSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        PlotSettingsDialog.setWindowTitle(_translate("PlotSettingsDialog", "Edit Plot Settings"))
        self.groupBox.setTitle(_translate("PlotSettingsDialog", "X-Axis"))
        self.groupBox_2.setTitle(_translate("PlotSettingsDialog", "Limits"))
        self.rbXAuto.setText(_translate("PlotSettingsDialog", "Auto"))
        self.label.setText(_translate("PlotSettingsDialog", "Min"))
        self.rbXManual.setText(_translate("PlotSettingsDialog", "Manual"))
        self.label_2.setText(_translate("PlotSettingsDialog", "Max"))
        self.groupBox_3.setTitle(_translate("PlotSettingsDialog", "Options"))
        self.chkXLog.setText(_translate("PlotSettingsDialog", "Log"))
        self.chkXGrid.setText(_translate("PlotSettingsDialog", "Grid"))
        self.groupBox_4.setTitle(_translate("PlotSettingsDialog", "Y-Axis"))
        self.groupBox_5.setTitle(_translate("PlotSettingsDialog", "Limits"))
        self.rbYAuto.setText(_translate("PlotSettingsDialog", "Auto"))
        self.label_3.setText(_translate("PlotSettingsDialog", "Min"))
        self.rbYManual.setText(_translate("PlotSettingsDialog", "Manual"))
        self.label_4.setText(_translate("PlotSettingsDialog", "Max"))
        self.groupBox_6.setTitle(_translate("PlotSettingsDialog", "Options"))
        self.chkYLog.setText(_translate("PlotSettingsDialog", "Log"))
        self.chkYGrid.setText(_translate("PlotSettingsDialog", "Grid"))
        self.groupBox_7.setTitle(_translate("PlotSettingsDialog", "Widget"))
        self.btnColor.setText(_translate("PlotSettingsDialog", "Line Color"))
        self.btnDone.setText(_translate("PlotSettingsDialog", "Done"))

