# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1397, 813)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitMain = QtWidgets.QSplitter(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.splitMain.setFont(font)
        self.splitMain.setOrientation(QtCore.Qt.Horizontal)
        self.splitMain.setObjectName("splitMain")
        self.frame_3 = QtWidgets.QFrame(self.splitMain)
        self.frame_3.setMinimumSize(QtCore.QSize(250, 250))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnStop = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
        self.btnStop.setSizePolicy(sizePolicy)
        self.btnStop.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnStop.setFont(font)
        self.btnStop.setStyleSheet("background-color: red")
        self.btnStop.setObjectName("btnStop")
        self.verticalLayout_5.addWidget(self.btnStop)
        self.splitSide = QtWidgets.QSplitter(self.frame_3)
        self.splitSide.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitSide.setOrientation(QtCore.Qt.Vertical)
        self.splitSide.setHandleWidth(10)
        self.splitSide.setObjectName("splitSide")
        self.gbPinnedPlot = QtWidgets.QGroupBox(self.splitSide)
        self.gbPinnedPlot.setMinimumSize(QtCore.QSize(0, 250))
        self.gbPinnedPlot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbPinnedPlot.setFont(font)
        self.gbPinnedPlot.setObjectName("gbPinnedPlot")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gbPinnedPlot)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pltPinned = PlotWidget(self.gbPinnedPlot)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pltPinned.setFont(font)
        self.pltPinned.setObjectName("pltPinned")
        self.verticalLayout_6.addWidget(self.pltPinned)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnResetPinnedPlot = QtWidgets.QPushButton(self.gbPinnedPlot)
        self.btnResetPinnedPlot.setObjectName("btnResetPinnedPlot")
        self.horizontalLayout_4.addWidget(self.btnResetPinnedPlot)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(self.splitSide)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblServPoll = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblServPoll.setFont(font)
        self.lblServPoll.setObjectName("lblServPoll")
        self.verticalLayout_2.addWidget(self.lblServPoll)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btnStartPause = QtWidgets.QPushButton(self.groupBox)
        self.btnStartPause.setObjectName("btnStartPause")
        self.horizontalLayout_3.addWidget(self.btnStartPause)
        self.btnStop_2 = QtWidgets.QPushButton(self.groupBox)
        self.btnStop_2.setObjectName("btnStop_2")
        self.horizontalLayout_3.addWidget(self.btnStop_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addWidget(self.splitSide)
        self.tabMain = TabWindowWidget(self.splitMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabMain.sizePolicy().hasHeightForWidth())
        self.tabMain.setSizePolicy(sizePolicy)
        self.tabMain.setMinimumSize(QtCore.QSize(500, 450))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.tabMain.setFont(font)
        self.tabMain.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabMain.setObjectName("tabMain")
        self.overview = QtWidgets.QWidget()
        self.overview.setObjectName("overview")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.overview)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scroller = QtWidgets.QScrollArea(self.overview)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scroller.setFont(font)
        self.scroller.setAutoFillBackground(False)
        self.scroller.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scroller.setWidgetResizable(True)
        self.scroller.setObjectName("scroller")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 830, 677))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.fmOverview = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fmOverview.setFont(font)
        self.fmOverview.setStyleSheet("")
        self.fmOverview.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmOverview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fmOverview.setObjectName("fmOverview")
        self.gridLayout_6.addWidget(self.fmOverview, 0, 0, 1, 1)
        self.scroller.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scroller, 0, 0, 1, 1)
        self.tabMain.addTab(self.overview, "")
        self.devices = QtWidgets.QWidget()
        self.devices.setObjectName("devices")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.devices)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitSettings = QtWidgets.QSplitter(self.devices)
        self.splitSettings.setOrientation(QtCore.Qt.Horizontal)
        self.splitSettings.setObjectName("splitSettings")
        self.layoutWidget = QtWidgets.QWidget(self.splitSettings)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.treeDevices = QtWidgets.QTreeWidget(self.layoutWidget)
        self.treeDevices.setFrameShadow(QtWidgets.QFrame.Plain)
        self.treeDevices.setColumnCount(2)
        self.treeDevices.setObjectName("treeDevices")
        self.treeDevices.headerItem().setText(0, "1")
        self.treeDevices.headerItem().setText(1, "2")
        self.treeDevices.header().setDefaultSectionSize(300)
        self.verticalLayout_4.addWidget(self.treeDevices)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnExpand = QtWidgets.QPushButton(self.layoutWidget)
        self.btnExpand.setObjectName("btnExpand")
        self.horizontalLayout.addWidget(self.btnExpand)
        self.btnCollapse = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCollapse.setObjectName("btnCollapse")
        self.horizontalLayout.addWidget(self.btnCollapse)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.fmDeviceSettings = QtWidgets.QFrame(self.splitSettings)
        self.fmDeviceSettings.setMinimumSize(QtCore.QSize(300, 0))
        self.fmDeviceSettings.setBaseSize(QtCore.QSize(600, 0))
        self.fmDeviceSettings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmDeviceSettings.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fmDeviceSettings.setObjectName("fmDeviceSettings")
        self.gridLayout_5.addWidget(self.splitSettings, 0, 0, 1, 1)
        self.tabMain.addTab(self.devices, "")
        self.plotting = QtWidgets.QWidget()
        self.plotting.setObjectName("plotting")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.plotting)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.plotting)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(1)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnSetupDevicePlots = QtWidgets.QPushButton(self.frame_4)
        self.btnSetupDevicePlots.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSetupDevicePlots.setFont(font)
        self.btnSetupDevicePlots.setFlat(False)
        self.btnSetupDevicePlots.setObjectName("btnSetupDevicePlots")
        self.horizontalLayout_2.addWidget(self.btnSetupDevicePlots)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.scrollArea = QtWidgets.QScrollArea(self.plotting)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scrollArea.setFont(font)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 834, 640))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.fmPlots = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fmPlots.setFont(font)
        self.fmPlots.setStyleSheet("")
        self.fmPlots.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmPlots.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fmPlots.setObjectName("fmPlots")
        self.gridLayout_4.addWidget(self.fmPlots, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.tabMain.addTab(self.plotting, "")
        self.procedures = QtWidgets.QWidget()
        self.procedures.setObjectName("procedures")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.procedures)
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btnAddProcedure = QtWidgets.QPushButton(self.procedures)
        self.btnAddProcedure.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAddProcedure.setFont(font)
        self.btnAddProcedure.setFlat(False)
        self.btnAddProcedure.setObjectName("btnAddProcedure")
        self.gridLayout_9.addWidget(self.btnAddProcedure, 0, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.procedures)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 834, 640))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.fmProcedures = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fmProcedures.setFont(font)
        self.fmProcedures.setStyleSheet("")
        self.fmProcedures.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fmProcedures.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fmProcedures.setObjectName("fmProcedures")
        self.vboxProcedures = QtWidgets.QVBoxLayout(self.fmProcedures)
        self.vboxProcedures.setContentsMargins(11, 11, 11, 11)
        self.vboxProcedures.setSpacing(6)
        self.vboxProcedures.setObjectName("vboxProcedures")
        self.gridLayout_10.addWidget(self.fmProcedures, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_9.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.tabMain.addTab(self.procedures, "")
        self.log = QtWidgets.QWidget()
        self.log.setObjectName("log")
        self.gridLayout = QtWidgets.QGridLayout(self.log)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.txtMessageLog = QtWidgets.QTextEdit(self.log)
        self.txtMessageLog.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.txtMessageLog.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txtMessageLog.setReadOnly(True)
        self.txtMessageLog.setObjectName("txtMessageLog")
        self.gridLayout.addWidget(self.txtMessageLog, 0, 0, 1, 1)
        self.tabMain.addTab(self.log, "")
        self.verticalLayout.addWidget(self.splitMain)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.toolBar.setFont(font)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1397, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Configure = QtWidgets.QMenu(self.menuBar)
        self.menu_Configure.setObjectName("menu_Configure")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuPrint = QtWidgets.QMenu(self.menuBar)
        self.menuPrint.setObjectName("menuPrint")
        MainWindow.setMenuBar(self.menuBar)
        self.btnQuit = QtWidgets.QAction(MainWindow)
        self.btnQuit.setObjectName("btnQuit")
        self.btnLoad = QtWidgets.QAction(MainWindow)
        self.btnLoad.setObjectName("btnLoad")
        self.btnSave = QtWidgets.QAction(MainWindow)
        self.btnSave.setObjectName("btnSave")
        self.btnSaveAs = QtWidgets.QAction(MainWindow)
        self.btnSaveAs.setObjectName("btnSaveAs")
        self.action_new_session = QtWidgets.QAction(MainWindow)
        self.action_new_session.setObjectName("action_new_session")
        self.action_load_session = QtWidgets.QAction(MainWindow)
        self.action_load_session.setObjectName("action_load_session")
        self.action_save_session = QtWidgets.QAction(MainWindow)
        self.action_save_session.setObjectName("action_save_session")
        self.action_save_session_as = QtWidgets.QAction(MainWindow)
        self.action_save_session_as.setObjectName("action_save_session_as")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_slack = QtWidgets.QAction(MainWindow)
        self.action_slack.setObjectName("action_slack")
        self.action_help = QtWidgets.QAction(MainWindow)
        self.action_help.setObjectName("action_help")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.btnAbout = QtWidgets.QAction(MainWindow)
        self.btnAbout.setObjectName("btnAbout")
        self.action_settings = QtWidgets.QAction(MainWindow)
        self.action_settings.setObjectName("action_settings")
        self.action_print = QtWidgets.QAction(MainWindow)
        self.action_print.setObjectName("action_print")
        self.action_print_preview = QtWidgets.QAction(MainWindow)
        self.action_print_preview.setObjectName("action_print_preview")
        self.toolBar.addAction(self.btnQuit)
        self.toolBar.addAction(self.btnLoad)
        self.toolBar.addAction(self.btnSave)
        self.toolBar.addAction(self.btnSaveAs)
        self.toolBar.addAction(self.btnAbout)
        self.menu_File.addAction(self.action_new_session)
        self.menu_File.addAction(self.action_load_session)
        self.menu_File.addAction(self.action_save_session)
        self.menu_File.addAction(self.action_save_session_as)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_quit)
        self.menu_Configure.addAction(self.action_slack)
        self.menu_Configure.addAction(self.action_settings)
        self.menuHelp.addAction(self.action_help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_about)
        self.menuPrint.addAction(self.action_print)
        self.menuPrint.addAction(self.action_print_preview)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Configure.menuAction())
        self.menuBar.addAction(self.menuPrint.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ion Source Control System"))
        self.btnStop.setText(_translate("MainWindow", "Emergency Stop"))
        self.gbPinnedPlot.setTitle(_translate("MainWindow", "Pinned Plot"))
        self.btnResetPinnedPlot.setText(_translate("MainWindow", "Reset"))
        self.groupBox.setTitle(_translate("MainWindow", "Server Communication"))
        self.lblServPoll.setText(_translate("MainWindow", "Server polling rate: 15 Hz"))
        self.btnStartPause.setText(_translate("MainWindow", "Start Polling"))
        self.btnStop_2.setText(_translate("MainWindow", "Stop"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.overview), _translate("MainWindow", "Overview"))
        self.treeDevices.setSortingEnabled(True)
        self.btnExpand.setText(_translate("MainWindow", "Expand All"))
        self.btnCollapse.setText(_translate("MainWindow", "Collapse All"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.devices), _translate("MainWindow", "Devices"))
        self.btnSetupDevicePlots.setText(_translate("MainWindow", "Choose Channels to Plot"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.plotting), _translate("MainWindow", "Plotting"))
        self.btnAddProcedure.setText(_translate("MainWindow", "Add Procedure"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.procedures), _translate("MainWindow", "Procedures"))
        self.tabMain.setTabText(self.tabMain.indexOf(self.log), _translate("MainWindow", "Message Log"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Configure.setTitle(_translate("MainWindow", "&Configure"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuPrint.setTitle(_translate("MainWindow", "Print"))
        self.btnQuit.setText(_translate("MainWindow", "Quit"))
        self.btnLoad.setText(_translate("MainWindow", "Load Session"))
        self.btnLoad.setToolTip(_translate("MainWindow", "Load Session"))
        self.btnSave.setText(_translate("MainWindow", "Save Session"))
        self.btnSaveAs.setText(_translate("MainWindow", "Save Session As"))
        self.action_new_session.setText(_translate("MainWindow", "&New Session"))
        self.action_load_session.setText(_translate("MainWindow", "&Load Session..."))
        self.action_save_session.setText(_translate("MainWindow", "&Save Session"))
        self.action_save_session_as.setText(_translate("MainWindow", "Save Session As..."))
        self.action_quit.setText(_translate("MainWindow", "&Quit"))
        self.action_slack.setText(_translate("MainWindow", "Slack..."))
        self.action_help.setText(_translate("MainWindow", "Help"))
        self.action_about.setText(_translate("MainWindow", "About"))
        self.btnAbout.setText(_translate("MainWindow", "About"))
        self.btnAbout.setToolTip(_translate("MainWindow", "About..."))
        self.action_settings.setText(_translate("MainWindow", "Settings..."))
        self.action_print.setText(_translate("MainWindow", "Print..."))
        self.action_print_preview.setText(_translate("MainWindow", "Print Preview..."))

from .widgets.TabWindowWidget import TabWindowWidget
from pyqtgraph import PlotWidget
